"""
Pydantic 스키마 정의 (API 요청/응답)
"""

# 기존 모델 (base.py에서 가져옴)
from .base import (
    ErrorResponse,
    SignUpRequest,
    LoginRequest,
    LoginResponse,
    UserResponse,
    CreateWorkspaceRequest,
    WorkspaceResponse,
    WorkspaceListResponse,
    CloneGitHubRequest,
    FileType,
    FileTreeItem,
    FileTreeResponse,
    FileContentResponse,
    UpdateFileContentRequest,
    UpdateFileContentResponse,
    SelectionRange,
    AIExplainRequest,
    AIExplainResponse,
    ChatMessage,
    AIChatRequest,
    AIChatResponse,
    # AI Modes (Agent, Plan, Ask, Debug)
    AIMode,
    TaskStep,
    AIPlanRequest,
    AIPlanResponse,
    AIAgentRequest,
    FileChange,
    AIAgentResponse,
    AIDebugRequest,
    BugFix,
    AIDebugResponse,
    # AI Advanced (Cursor-like)
    ContextType,
    ContextItem,
    AIAdvancedChatRequest,
    AIAdvancedChatResponse,
    ImageUploadResponse,
    ImageAnalysisRequest,
    ImageAnalysisResponse,
    ContextSuggestRequest,
    ContextSuggestion,
    ContextSuggestResponse,
    # Rewrite
    AIRewriteRequest,
    AIRewriteResponse,
    PatchValidateRequest,
    PatchValidateResponse,
    PatchApplyRequest,
    PatchApplyResponse,
    WSMessageType,
    WSMessage,
    ServerType,
    ServerStatus,
    AuthType,
    RegisterServerRequest,
    ServerResponse,
    TestConnectionResponse,
    PlacementPolicyType,
    PlacementRequest,
)

# 컨테이너 모델
from .container import (
    ContainerStatus,
    ContainerImage,
    ResourceLimits,
    ContainerConfig,
    StartContainerRequest,
    StopContainerRequest,
    RestartContainerRequest,
    ExecuteCommandRequest,
    ContainerStatusResponse,
    ContainerLogsResponse,
    ExecuteCommandResponse,
    ContainerActionResponse,
    # SSH 관련
    SSHConnectionInfo,
    SSHConnectionResponse,
    SetupSSHKeyRequest,
    SetupSSHPasswordRequest,
    SSHKeyResponse,
    GenerateSSHKeyRequest,
    GenerateSSHKeyResponse,
)

__all__ = [
    # Common
    "ErrorResponse",
    # Auth
    "SignUpRequest",
    "LoginRequest",
    "LoginResponse",
    "UserResponse",
    # Workspaces
    "CreateWorkspaceRequest",
    "WorkspaceResponse",
    "WorkspaceListResponse",
    "CloneGitHubRequest",
    # Files
    "FileType",
    "FileTreeItem",
    "FileTreeResponse",
    "FileContentResponse",
    "UpdateFileContentRequest",
    "UpdateFileContentResponse",
    # AI - Basic
    "SelectionRange",
    "AIExplainRequest",
    "AIExplainResponse",
    "ChatMessage",
    "AIChatRequest",
    "AIChatResponse",
    "AIRewriteRequest",
    "AIRewriteResponse",
    # AI - Modes (Agent, Plan, Ask, Debug)
    "AIMode",
    "TaskStep",
    "AIPlanRequest",
    "AIPlanResponse",
    "AIAgentRequest",
    "FileChange",
    "AIAgentResponse",
    "AIDebugRequest",
    "BugFix",
    "AIDebugResponse",
    # AI - Advanced (Cursor-like)
    "ContextType",
    "ContextItem",
    "AIAdvancedChatRequest",
    "AIAdvancedChatResponse",
    "ImageUploadResponse",
    "ImageAnalysisRequest",
    "ImageAnalysisResponse",
    "ContextSuggestRequest",
    "ContextSuggestion",
    "ContextSuggestResponse",
    # Patch
    "PatchValidateRequest",
    "PatchValidateResponse",
    "PatchApplyRequest",
    "PatchApplyResponse",
    # WebSocket
    "WSMessageType",
    "WSMessage",
    # Admin / Infrastructure
    "ServerType",
    "ServerStatus",
    "AuthType",
    "RegisterServerRequest",
    "ServerResponse",
    "TestConnectionResponse",
    "PlacementPolicyType",
    "PlacementRequest",
    # Container
    "ContainerStatus",
    "ContainerImage",
    "ResourceLimits",
    "ContainerConfig",
    "StartContainerRequest",
    "StopContainerRequest",
    "RestartContainerRequest",
    "ExecuteCommandRequest",
    "ContainerStatusResponse",
    "ContainerLogsResponse",
    "ExecuteCommandResponse",
    "ContainerActionResponse",
    # SSH
    "SSHConnectionInfo",
    "SSHConnectionResponse",
    "SetupSSHKeyRequest",
    "SetupSSHPasswordRequest",
    "SSHKeyResponse",
    "GenerateSSHKeyRequest",
    "GenerateSSHKeyResponse",
]
